### ISSUE TITLE
MIME Type error on importing Amber Visual via unpkg.

### ISSUE THREAD

**Issue by anthonypenna** [bitrockteam/amber-visual#6]
# MIME Type error on importing Amber Visual via unpkg.

### Steps to reproduce:
- Copy **unpkg** url from https://amber.bitrock.it/introduction/install/#visual
- Paste the url in a link tag:
`<link rel="stylesheet" href="unpkg.com/@amberds/visual@1.0.1/dist/index.css" />`

### Expected behaviour:
Correctly import and apply Amber Visual styles.

### Actual behaviour:
**Exception**: `Refused to apply style from 'http://127.0.0.1:5500/unpkg.com/@amber-ds/visual@1.0.1/dist/index.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

### Fix:

Edit the **unpkg** url on https://amber.bitrock.it by adding an `https://` prefix.

**Comment by moebiusmania** [comment]
fixed here https://github.com/bitrockteam/amber-website/commit/10dc37a320203a430a979bc53edd209bbcd8f4ed
